window.GIVVY_BUNDLED_LOGOS = new Set([
  "akunbemofficial.jpeg", "aminnahskincare2.jpeg", "amnhskincare.jpeg",
  "angelafindsdeals.jpeg", "ankerofficial.jpeg", "bareminerals.jpeg",
  "basuragang.jpeg", "blitzbreakzz.jpeg", "brp2019.jpeg", "buxomcosmetics.jpeg",
  "cakesbody.jpeg", "cardboys2.jpeg", "casemate.jpeg", "casemate.png",
  "chocboxla.jpeg", "crazybeautifulhomeschool.jpeg", "crocsshop_us.jpeg",
  "danimorgansboutique.jpeg", "edikted.jpeg", "ellobyevol.jpeg", "ellohoney.jpeg",
  "elloparty.jpeg", "fanttik_official.jpeg", "feelingirlus.jpeg", "fhiheat.jpeg",
  "filthyhits.jpeg", "gghobbycard.jpeg", "glamnetic.jpeg", "gomrpen.png",
  "gurunandaofficial.jpeg", "happyplantclub.jpeg", "heydudeshop_us .jpeg",
  "heydudeshop_us.jpeg", "hsia_official.jpeg", "hsn.jpeg", "hulkenbag.jpeg",
  "ibrasgreenwood.jpeg", "inspiredpeachy.jpeg", "joocarus.jpeg", "justjames.jpeg",
  "karmanepalcrafts.jpeg", "kimchichic.jpeg", "kindnessmom.jpeg",
  "kirbykosmetics.jpeg", "kodakphotoprinter.jpeg", "linensandhutch.jpeg",
  "lurellacosmetics.jpeg", "madelisabeth.jpeg", "magicjohn_officialshop.jpeg",
  "makeuperaser.jpeg", "makeuprevolutionusa.jpeg", "maskertgirl.jpeg",
  "meobubble.jpeg", "merachus.jpeg", "merachusa.jpeg", "miraclegro.jpeg",
  "moziwash.jpeg", "my_chefman.jpeg", "mybag_obsession.jpeg",
  "nailphoria_official.jpeg", "nailvesta_official.jpeg", "nakerybeauty.jpeg",
  "naturium.jpeg", "ninetynine_dreams.jpeg", "ninjakitchen.jpeg",
  "notpolish_nail.jpeg", "nox_jewels_sf.jpeg", "nycitysucculents.jpeg",
  "oeak_bras.jpeg", "oeak_official.jpeg", "ofracosmetics.jpeg", "ohclem.jpeg",
  "otbreaks.jpeg", "planails.jpeg", "pokegramnet.jpeg", "portlandleather.jpeg",
  "prequelskin.jpeg", "prestonandtina7.jpeg", "projectcloudofficial.jpeg",
  "prolashofficial.jpeg", "promakenails.jpeg", "publiquity.jpeg",
  "pullingpokemon.jpeg", "qvc.jpeg", "qvcbeauty.jpeg", "qvcfashion.jpeg",
  "qvchome.jpeg", "qvcjewelry.jpeg", "ripnhitts.jpeg", "salefashion11.jpeg",
  "shannahmarie77.jpeg", "shapellxofficial.jpeg", "sharkbeauty.jpeg",
  "sharkhome.jpeg", "shdwballtcg.jpeg", "shoptaniri.jpeg", "spxubzus.jpeg",
  "sterlingforever.jpeg", "surfsidesucculents.jpeg", "t3micro.jpeg",
  "tabithabrinkman.jpeg", "thatangelavibe.png", "theamandagray.jpeg",
  "thehypeboutiqueshop.jpeg", "thepopcornshop.jpeg", "toms.jpeg", "toniesus.jpeg",
  "tymobeauty_official.jpeg", "vaquerasoutfitters.jpeg", "vaulthousetcg.jpeg",
  "watercolors_tressahair.jpeg", "wonderskin.jpeg", "yappyapparel.jpeg",
  "yolie7265.jpeg", "yvaexpressions.jpeg"
]);
